const versions={'Android 8.1':[['Nexus 5X','LG'],['Pixel 2','Google']],'Android 10':[['Pixel 4','Google'],['Galaxy S10','Samsung']],'Android 12':[['Pixel 6','Google'],['Galaxy S21','Samsung']],'Android 13':[['Pixel 7','Google'],['Galaxy A54','Samsung']],'Android 14':[['Pixel 8','Google'],['Galaxy S23','Samsung']]};
const phases=['WELCOME','NETWORK','ACCOUNT_GATE','RESTORE_CHECK','FINISHED'];
const $=id=>document.getElementById(id);
Object.keys(versions).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;$('androidVersion').appendChild(o)});
let wizardIndex=0;
function populateModels(){ $('deviceModel').innerHTML=''; for(const [m] of versions[$('androidVersion').value]){const o=document.createElement('option');o.value=m;o.textContent=m;$('deviceModel').appendChild(o)} update(); }
function update(){const type=$('lockType').value;const labels={pattern:'Introduce el patrón para continuar',password:'Introduce la contraseña para continuar',google:'Verifica la cuenta Google para continuar'};$('lockSubtitle').textContent=labels[type];$('phoneBrand').textContent=$('deviceModel').value+' · '+$('androidVersion').value;$('wizardPhase').textContent=phases[wizardIndex];$('observations').innerHTML=['Setup Wizard: máquina de estados local y observable','Account gate: representado como política, no bypassable','FRP: condición de protección independiente del Wizard','ADB authorization: modelado independientemente de FRP','Bootloader: LOCKED por defecto','No se accede a dispositivo, USB, credenciales ni cuentas reales'].map(x=>`<li>${x}</li>`).join('');}
function reset(){wizardIndex=0;$('provisioning').textContent='PROVISIONED';$('frp').textContent='ACTIVE';$('adb').textContent='UNAUTHORIZED';$('bootloader').textContent='LOCKED';$('result').textContent='BLOCKED';$('screenTitle').textContent='Setup Wizard';$('eventLog').textContent='Esperando evento…';update();}
$('androidVersion').addEventListener('change',populateModels);$('deviceModel').addEventListener('change',update);$('lockType').addEventListener('change',update);$('reset').addEventListener('click',reset);
$('simulate').addEventListener('click',()=>{wizardIndex=Math.min(wizardIndex+1,phases.length-1);const blocked=wizardIndex>=2;$('wizardPhase').textContent=phases[wizardIndex];$('screenTitle').textContent=blocked?'Cuenta requerida':'Setup Wizard';$('result').textContent=blocked?'BLOCKED':'IN_PROGRESS';const event={timestamp:new Date().toISOString(),component:'setup-wizard',phase:phases[wizardIndex],version:$('androidVersion').value,model:$('deviceModel').value,lock:$('lockType').value,provisioning:$('provisioning').textContent,frp:$('frp').textContent,adb:$('adb').textContent,bootloader:$('bootloader').textContent,result:$('result').textContent,scope:'controlled-simulator-only'};$('eventLog').textContent=JSON.stringify(event,null,2)});
$('clear').addEventListener('click',()=>{$('eventLog').textContent='Evento limpiado.'});
$('export').addEventListener('click',()=>{const data=$('eventLog').textContent;if(!data.startsWith('{'))return;const blob=new Blob([data],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='setup-wizard-evidence.json';a.click();URL.revokeObjectURL(a.href)});
$('androidVersion').value='Android 13';populateModels();$('deviceModel').value='Pixel 7';update();
