const versions={'Android 8.1':[['Nexus 5X','LG'],['Pixel 2','Google']],'Android 10':[['Pixel 4','Google'],['Galaxy S10','Samsung']],'Android 12':[['Pixel 6','Google'],['Galaxy S21','Samsung']],'Android 13':[['Pixel 7','Google'],['Galaxy A54','Samsung']],'Android 14':[['Pixel 8','Google'],['Galaxy S23','Samsung']]};
const phases=SetupWizardMachine.phases;
const $=id=>document.getElementById(id);
Object.keys(versions).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;$('androidVersion').appendChild(o)});
let wizardState=SetupWizardMachine.initialState();
function populateModels(){ $('deviceModel').innerHTML=''; for(const [m] of versions[$('androidVersion').value]){const o=document.createElement('option');o.value=m;o.textContent=m;$('deviceModel').appendChild(o)} update(); }
function update(){const type=$('lockType').value;const labels={pattern:'Introduce el patrón para continuar',password:'Introduce la contraseña para continuar',google:'Verifica la cuenta Google para continuar'};$('lockSubtitle').textContent=labels[type];$('phoneBrand').textContent=$('deviceModel').value+' · '+$('androidVersion').value;$('wizardPhase').textContent=wizardState.phase;$('provisioning').textContent=wizardState.provisioning;$('frp').textContent=wizardState.frp;$('adb').textContent=wizardState.adb;$('bootloader').textContent=wizardState.bootloader;$('result').textContent=wizardState.result;const validation=SetupWizardMachine.validate(wizardState);$('invariantStatus').textContent=validation.valid?'VALID':'VIOLATION';$('observations').innerHTML=['Setup Wizard: máquina de estados local y observable','Transiciones permitidas: '+phases.join(' → '),'Account gate: representado como política, no bypassable','FRP: condición de protección independiente del Wizard','ADB authorization: modelado independientemente de FRP','Bootloader: LOCKED por defecto','Invariantes: '+(validation.valid?'válidas':'violadas'),'No se accede a dispositivo, USB, credenciales ni cuentas reales'].map(x=>`<li>${x}</li>`).join('');}
function reset(){wizardState=SetupWizardMachine.initialState();$('screenTitle').textContent='Setup Wizard';$('eventLog').textContent='Esperando evento…';update();}
$('androidVersion').addEventListener('change',populateModels);$('deviceModel').addEventListener('change',update);$('lockType').addEventListener('change',update);$('reset').addEventListener('click',reset);
$('simulate').addEventListener('click',()=>{wizardState=SetupWizardMachine.transition(wizardState);const validation=SetupWizardMachine.validate(wizardState);$('wizardPhase').textContent=wizardState.phase;$('screenTitle').textContent=wizardState.phase==='ACCOUNT_GATE'?'Cuenta requerida':'Setup Wizard';const event={timestamp:new Date().toISOString(),component:'setup-wizard',phase:wizardState.phase,allowedTransitions:SetupWizardMachine.transitions[wizardState.phase]||[],version:$('androidVersion').value,model:$('deviceModel').value,lock:$('lockType').value,provisioning:wizardState.provisioning,frp:wizardState.frp,adb:wizardState.adb,bootloader:wizardState.bootloader,result:wizardState.result,invariants:validation,scope:'controlled-simulator-only'};$('eventLog').textContent=JSON.stringify(event,null,2);update();});
$('clear').addEventListener('click',()=>{$('eventLog').textContent='Evento limpiado.'});
$('export').addEventListener('click',()=>{const data=$('eventLog').textContent;if(!data.startsWith('{'))return;const blob=new Blob([data],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='setup-wizard-evidence.json';a.click();URL.revokeObjectURL(a.href)});
$('androidVersion').value='Android 13';populateModels();$('deviceModel').value='Pixel 7';update();
